# Generated by Django 3.0.8 on 2020-07-20 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analyst',
            fields=[
                ('AnalystCode', models.BigIntegerField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=50, null=True)),
                ('Password', models.CharField(max_length=60)),
                ('RegisterDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('PerNationalId', models.BigIntegerField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=50, null=True)),
                ('Password', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('SynCode', models.BigIntegerField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=50, null=True)),
                ('Password', models.CharField(max_length=60)),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HealthMinistryLicenseCenter',
            fields=[
                ('CenterCode', models.BigIntegerField(primary_key=True, serialize=False)),
                ('CenterName', models.CharField(max_length=60)),
                ('CenterType', models.CharField(max_length=20)),
                ('CenterGov', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='HealthMinistryLicenseLab',
            fields=[
                ('MinLabCode', models.BigIntegerField(primary_key=True, serialize=False)),
                ('LabName', models.CharField(max_length=60, null=True)),
                ('LabType', models.CharField(max_length=20, null=True)),
                ('LabGov', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('LabCode', models.BigIntegerField(primary_key=True, serialize=False)),
                ('LabName', models.CharField(max_length=60)),
                ('LabUserName', models.CharField(max_length=50, null=True)),
                ('LabPassword', models.CharField(max_length=60)),
                ('LabGov', models.CharField(max_length=40)),
                ('CurrentAddress', models.CharField(max_length=120)),
                ('FirstPhone', models.BigIntegerField()),
                ('SecoundPhone', models.BigIntegerField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalAnalystLicense',
            fields=[
                ('AnalystCode', models.BigIntegerField(primary_key=True, serialize=False)),
                ('NationalId', models.CharField(max_length=30)),
                ('Specialization1', models.CharField(max_length=50)),
                ('Specialization2', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalCenter',
            fields=[
                ('CenterCode', models.BigIntegerField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=50, null=True)),
                ('Password', models.CharField(max_length=60)),
                ('CenterName', models.CharField(max_length=60)),
                ('CenterGov', models.CharField(max_length=40)),
                ('CurrentAddress', models.CharField(max_length=120)),
                ('FirstPhone', models.BigIntegerField()),
                ('SecoundPhone', models.BigIntegerField()),
                ('RegisteredDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('UpdateDate', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalSyndicateLicense',
            fields=[
                ('SynCode', models.BigIntegerField(primary_key=True, serialize=False)),
                ('NationalId', models.CharField(max_length=30)),
                ('Specialization1', models.CharField(max_length=50)),
                ('Specialization2', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SynCode', models.CharField(max_length=30)),
                ('DoctorName', models.CharField(max_length=60)),
                ('Specialization1', models.CharField(max_length=50)),
                ('Specialization2', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PersonMedicalCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CurrentTime', models.DateTimeField(auto_now_add=True)),
                ('CenterCode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.MedicalCenter')),
                ('PerNationalId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.Citizen')),
            ],
        ),
        migrations.CreateModel(
            name='PersonLab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('LabCode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.Laboratory')),
                ('PerNationalId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.Citizen')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.AutoField(auto_created=False, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=60)),
                ('Gender', models.CharField(max_length=10)),
                ('Job', models.CharField(max_length=50)),
                ('BirthGov', models.CharField(max_length=40)),
                ('BirthDate', models.DateField(null=True)),
                ('CurrentGov', models.CharField(max_length=40)),
                ('CurrentAddress', models.CharField(max_length=120)),
                ('FirstPhone', models.BigIntegerField()),
                ('SecoundPhone', models.BigIntegerField()),
                ('Email', models.EmailField(max_length=60)),
                ('FirstRelName', models.CharField(max_length=60)),
                ('FirstRelPhone', models.BigIntegerField()),
                ('SecoundRelName', models.CharField(max_length=60)),
                ('SecoundRelPhone', models.BigIntegerField()),
                ('PassportNo', models.BigIntegerField(null=True)),
                ('BloodGroup', models.CharField(max_length=5, null=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('PerNationalId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.Citizen')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CurrentTime', models.DateTimeField(auto_now_add=True)),
                ('SynCode', models.CharField(max_length=30)),
                ('CenterCode', models.CharField(max_length=30)),
                ('CenterName', models.CharField(max_length=60)),
                ('RecordDate', models.DateTimeField(auto_now_add=True)),
                ('MedicalReport', models.TextField(null=True)),
                ('Treatment', models.TextField(null=True)),
                ('LabCode', models.CharField(max_length=30)),
                ('LabName', models.CharField(max_length=60)),
                ('AnalysisReport', models.TextField(null=True)),
                ('RaysReport', models.TextField(null=True)),
                ('PerNationalId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.Citizen')),
            ],
        ),
        migrations.CreateModel(
            name='DocWorkOnCenterHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SynCode', models.CharField(max_length=30)),
                ('WorkOnDate', models.DateTimeField(auto_now_add=True)),
                ('RemoveDate', models.DateTimeField(null=True)),
                ('CenterCode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.MedicalCenter')),
            ],
        ),
        migrations.CreateModel(
            name='DocWorkOnCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WorkOnDate', models.DateTimeField(auto_now_add=True)),
                ('CenterCode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.MedicalCenter')),
                ('SynCode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CurrentTime', models.DateTimeField(auto_now_add=True)),
                ('PerNationalId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.Citizen')),
                ('SynCode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='AnalystWorkOnLab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WorkOnDate', models.DateTimeField(auto_now_add=True)),
                ('AnalystCode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.Analyst')),
                ('LabCode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.Laboratory')),
            ],
        ),
        migrations.CreateModel(
            name='AnalystLabHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AnalystCode', models.CharField(max_length=30)),
                ('AnalystAddDate', models.DateTimeField(auto_now_add=True)),
                ('RemoveAnalystDate', models.DateTimeField(null=True)),
                ('LabCode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.Laboratory')),
            ],
        ),
    ]
