# Generated by Django 3.0.8 on 2020-07-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthministrylicensecenter',
            name='Password',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='healthministrylicenselab',
            name='Password',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='medicalanalystlicense',
            name='Password',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='medicalsyndicatelicense',
            name='Password',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
