# Generated by Django 3.0.8 on 2020-07-24 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200723_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
