# Generated by Django 3.0.8 on 2020-07-24 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200724_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Password',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
