# Generated by Django 3.0.8 on 2020-07-26 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20200725_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='PerNationalId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='website.Citizen'),
        ),
    ]
