# Generated by Django 3.0.8 on 2020-07-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20200726_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalhistory',
            name='DoctorName',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
