# Generated by Django 3.0.8 on 2020-07-27 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_medicalhistory_doctorname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalcenter',
            old_name='UserName',
            new_name='CenterType',
        ),
    ]
