# Generated by Django 3.0.8 on 2020-07-28 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20200728_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docworkoncenterhistory',
            name='CenterCode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='website.MedicalCenter'),
        ),
    ]
