# Generated by Django 3.0.8 on 2020-07-28 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20200728_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='DoctorNationalId',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
