# Generated by Django 3.0.8 on 2020-07-28 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_doctor_doctornationalid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docworkoncenter',
            name='CenterCode',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='docworkoncenterhistory',
            name='CenterCode',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
