# Generated by Django 3.0.8 on 2020-07-29 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20200728_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docworkoncenter',
            name='SynCode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='website.Doctor'),
        ),
    ]
