# Generated by Django 3.0.8 on 2020-07-29 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_auto_20200729_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='docworkoncenter',
            name='DoctorName',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='docworkoncenter',
            name='Specialization1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='docworkoncenter',
            name='Specialization2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='docworkoncenterhistory',
            name='DoctorName',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='docworkoncenterhistory',
            name='Specialization1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='docworkoncenterhistory',
            name='Specialization2',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
