# Generated by Django 3.0.8 on 2020-07-29 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_auto_20200729_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='docworkoncenter',
            name='DoctorNationalId',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='docworkoncenterhistory',
            name='DoctorNationalId',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
