# Generated by Django 3.0.8 on 2020-07-30 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_auto_20200729_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='analystlabhistory',
            name='AnalystName',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='analystlabhistory',
            name='AnalystNationalId',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='analystlabhistory',
            name='Specialization1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='analystlabhistory',
            name='Specialization2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='analystworkonlab',
            name='AnalystName',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='analystworkonlab',
            name='AnalystNationalId',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='analystworkonlab',
            name='Specialization1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='analystworkonlab',
            name='Specialization2',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
