# Generated by Django 3.0.8 on 2020-07-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_auto_20200730_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalhistory',
            name='PassportNo',
            field=models.BigIntegerField(null=True),
        ),
    ]
