# Generated by Django 3.0.8 on 2020-08-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_medicalhistory_passportno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyst',
            name='RegisterDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
