# Generated by Django 3.0.8 on 2020-08-03 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_auto_20200802_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='PerNationalId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='website.Citizen'),
        ),
    ]
