# Generated by Django 3.0.8 on 2020-08-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_auto_20200803_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personlab',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
