# Generated by Django 3.0.8 on 2020-08-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_auto_20200803_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
