# Generated by Django 3.0.8 on 2020-08-04 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_auto_20200804_0503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalhistory',
            name='PassportNo',
        ),
    ]
