# Generated by Django 3.0.8 on 2020-08-04 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_remove_medicalhistory_passportno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='UserName',
        ),
    ]
