# Generated by Django 3.0.6 on 2020-08-08 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_remove_doctor_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
